# Generated by Django 4.2.7 on 2026-08-26

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("oss", "0014_widen_filerecord_url_fields"),
        ("tabtinspace", "0145_shared_resource_placement_dismissed"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "project_name_snapshot",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("title", models.CharField(max_length=255)),
                ("brief", models.TextField(blank=True, default="")),
                (
                    "lifecycle_status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("preparing", "准备中"),
                            ("recording", "记录中"),
                            ("paused", "已暂停"),
                            ("stopped", "已停止"),
                            ("cancelled", "已取消"),
                            ("interrupted", "异常中断"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "audio_sync_policy",
                    models.CharField(
                        choices=[
                            ("local_only", "仅本地"),
                            ("sync_audio", "同步音频"),
                        ],
                        default="local_only",
                        max_length=20,
                    ),
                ),
                ("copilot_initially_enabled", models.BooleanField(default=False)),
                ("copilot_enabled", models.BooleanField(default=False)),
                ("consent_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveBigIntegerField(default=0)),
                ("version", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_sessions",
                        to="tabtinspace.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meeting_sessions",
                        to="tabtinspace.project",
                    ),
                ),
            ],
            options={
                "db_table": "meeting_session",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MeetingTrack",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("local", "麦克风"), ("remote", "系统音频")],
                        max_length=16,
                    ),
                ),
                (
                    "capture_status",
                    models.CharField(
                        choices=[
                            ("pending", "待采集"),
                            ("active", "采集中"),
                            ("paused", "已暂停"),
                            ("completed", "完整"),
                            ("interrupted", "已中断"),
                            ("failed", "失败"),
                            ("missing", "缺失"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "storage_status",
                    models.CharField(
                        choices=[
                            ("local_only", "仅本地"),
                            ("uploading", "上传中"),
                            ("synced", "已同步"),
                            ("missing", "文件缺失"),
                            ("deleted", "已删除"),
                        ],
                        db_index=True,
                        default="local_only",
                        max_length=20,
                    ),
                ),
                ("local_available", models.BooleanField(default=False)),
                ("device_id", models.CharField(blank=True, default="", max_length=255)),
                ("device_label", models.CharField(blank=True, default="", max_length=255)),
                ("sample_rate", models.PositiveIntegerField(default=0)),
                ("channel_count", models.PositiveSmallIntegerField(default=0)),
                ("codec", models.CharField(blank=True, default="", max_length=32)),
                ("container", models.CharField(blank=True, default="", max_length=32)),
                ("duration_ms", models.PositiveBigIntegerField(default=0)),
                ("file_size", models.PositiveBigIntegerField(default=0)),
                (
                    "content_hash",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                ("last_checkpoint_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meeting_tracks",
                        to="oss.filerecord",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="meetings.meetingsession",
                    ),
                ),
            ],
            options={"db_table": "meeting_track"},
        ),
        migrations.CreateModel(
            name="MeetingTranscriptRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("realtime", "实时转写"),
                            ("post_process", "会后转写"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待转写"),
                            ("running", "转写中"),
                            ("completed", "已完成"),
                            ("partial", "部分完成"),
                            ("failed", "失败"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("provider", models.CharField(blank=True, default="", max_length=64)),
                ("model", models.CharField(blank=True, default="", max_length=128)),
                ("language", models.CharField(blank=True, default="", max_length=32)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                ("error_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcript_runs",
                        to="meetings.meetingsession",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcript_runs",
                        to="meetings.meetingtrack",
                    ),
                ),
            ],
            options={
                "db_table": "meeting_transcript_run",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MeetingTranscriptSegment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_id", models.CharField(max_length=128)),
                (
                    "source",
                    models.CharField(
                        choices=[("local", "麦克风"), ("remote", "系统音频")],
                        max_length=16,
                    ),
                ),
                ("speaker_key", models.CharField(blank=True, default="", max_length=128)),
                ("start_ms", models.PositiveBigIntegerField()),
                ("end_ms", models.PositiveBigIntegerField()),
                ("raw_text", models.TextField(blank=True, default="")),
                ("edited_text", models.TextField(blank=True, default="")),
                ("is_final", models.BooleanField(db_index=True, default=False)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "edited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="edited_meeting_transcript_segments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="meetings.meetingtranscriptrun",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcript_segments",
                        to="meetings.meetingsession",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcript_segments",
                        to="meetings.meetingtrack",
                    ),
                ),
            ],
            options={
                "db_table": "meeting_transcript_segment",
                "ordering": ["start_ms", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["session", "start_ms"],
                        name="meet_tseg_session_time_idx",
                    ),
                    models.Index(
                        fields=["session", "source", "is_final"],
                        name="meet_tseg_source_final_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="meetingtranscriptsegment",
            constraint=models.UniqueConstraint(
                fields=("run", "external_id"),
                name="meet_tseg_run_external_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="meetingtranscriptsegment",
            constraint=models.CheckConstraint(
                check=models.Q(("end_ms__gte", models.F("start_ms"))),
                name="meet_tseg_time_order_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="meetingtranscriptrun",
            index=models.Index(
                fields=["session", "mode", "status"],
                name="meet_trun_session_mode_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="meetingtrack",
            index=models.Index(
                fields=["session", "capture_status"],
                name="meet_track_session_state_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="meetingtrack",
            constraint=models.UniqueConstraint(
                fields=("session", "source"),
                name="meet_track_session_source_uq",
            ),
        ),
        migrations.AddIndex(
            model_name="meetingsession",
            index=models.Index(
                fields=["organization", "created_by", "-created_at"],
                name="meet_sess_org_owner_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="meetingsession",
            index=models.Index(
                fields=["project", "-created_at"],
                name="meet_sess_project_idx",
            ),
        ),
    ]
